function [imdsTrain, imdsValidation, numClasses] = dataPretreat(s, normal)
    %% 数据增广
    % normal=1时不做放大缩小偏移
    imds = imageDatastore('+part3/train', ...
        'IncludeSubfolders',true, ...
        'LabelSource','foldernames'); 
    [imdsTrain,imdsValidation] = splitEachLabel(imds,0.7);
    numClasses = numel(categories(imdsTrain.Labels));
    pixelRange = [-1 1];
    scaleRange = [0.9 1.1];
    imageAugmenter = imageDataAugmenter( ...
        'RandXReflection',true, ...
        'RandXTranslation',pixelRange, ...
        'RandYTranslation',pixelRange, ...
        'RandXScale',scaleRange, ...
        'RandYScale',scaleRange);
    if normal == 1
        imdsTrain = augmentedImageDatastore(s(1:2),imdsTrain);
        imdsValidation = augmentedImageDatastore(s(1:2),imdsValidation);
    else
        imdsTrain = augmentedImageDatastore(s(1:2),imdsTrain, ...
            'DataAugmentation',imageAugmenter);
        imdsValidation = augmentedImageDatastore(s(1:2),imdsValidation, ...
            'DataAugmentation',imageAugmenter);
    end

end