
function trainLenet()
    %% LeNet-5迁移学习
    layers = lenet5TLfun();
    inputSize = layers(1).InputSize;
    [imdsTrain, imdsValidation, numClasses] = part3.dataPretreat(inputSize, 0);
    options = trainingOptions('sgdm', ...
        'LearnRateSchedule','piecewise', ...
        'LearnRateDropFactor',0.1, ...
        'LearnRateDropPeriod',30,...
        'MiniBatchSize',128, ...
        'MaxEpochs',30, ...
        'InitialLearnRate',5e-4, ...
        'ValidationData',imdsValidation, ...
        'ValidationFrequency',3, ...
        'Shuffle','every-epoch', ...
        'Verbose',false, ...
        'Plots','training-progress');
    net = trainNetwork(imdsTrain, layers, options);
    
    % 保存网络结果
    myLenet = net;
    save ('myLenet.mat', 'myLenet');
    
end
